### ISSUE TITLE
PHP 8.2 deprecation notice - Using ${var} in strings is deprecated

### ISSUE THREAD

**Issue by claytoncollie** [functionsfile/uncomment#3]
Hello. 

I am upgrading some sites to use PHP 8.2 and this deprecation notice is being thrown in the error logs.

`[18-Dec-2023 16:50:53 UTC] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /wp-content/plugins/uncomment/includes/admin.php on line 178
`

**Comment by barryceelen** [comment]
Thanks for reporting @claytoncollie! This issue has been fixed in version 1.2.1.
